"""Constants for the Stellabook arXiv client and notebook generation."""

ARXIV_API_BASE_URL = "https://export.arxiv.org/api/query"
ARXIV_RATE_LIMIT_SECONDS = 3.0
ARXIV_DEFAULT_MAX_RESULTS = 10
ARXIV_MAX_RESULTS_LIMIT = 100

ANTHROPIC_RESEARCH_MODEL = "claude-sonnet-4-20250514"
ANTHROPIC_RESEARCH_MAX_TOKENS = 4096
ANTHROPIC_NOTEBOOK_MODEL = "claude-sonnet-4-20250514"
ANTHROPIC_NOTEBOOK_MAX_TOKENS = 16384

NOTEBOOK_NBFORMAT_VERSION = 4
NOTEBOOK_NBFORMAT_MINOR = 5

FIGURE_MIN_DIMENSION = 100
FIGURE_MAX_COUNT = 20
FIGURE_INLINE_MAX_BYTES = 40_960
FIGURE_SCALED_MIN_DIMENSION = 600
